# Generated by Django 3.1.6 on 2021-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(upload_to='media/ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='media/recipe'),
        ),
    ]
