# Generated by Django 3.1.6 on 2021-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210314_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='recipe',
        ),
        migrations.AddField(
            model_name='cart',
            name='recipe',
            field=models.ManyToManyField(to='recipe.Recipe'),
        ),
    ]
