# Generated by Django 3.1.6 on 2021-03-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20210317_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartingredient',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='cartingredient',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredients'),
            preserve_default=False,
        ),
    ]
