# Generated by Django 2.2 on 2021-03-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_ingredients_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_list',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
    ]
